### PR TITLE
DAT-18604 : fix Docker Build and Push to AWS Marketplace

### PR DESCRIPTION
**Pull request by sayaliM0412**
1. fix: `.github/utils/submit-aws-mp-listing.sh`: remove echo command as it was giving false positive
2. fix: `.github/workflows/deploy-extension-to-marketplace.yml`: Check if tag exists in ECR and fix corresponding script

### CODE REVIEW

**Review by abrackx — APPROVED** [review]
Idk what this does but :shipit:

**Comment by abrackx** [comment]
Looks like there are some conflicts to resolve though

**Comment by sayaliM0412** [comment]
> Idk what this does but :shipit:

when the workflow file is run multiple time, it complains that the tag already exists in AWS ECR. Here I am checking if the tag already exists, then skip it.

**Comment by sayaliM0412** [comment]
PR not required as one or the other tag would always exist. 
Real issue fixed for DAT-18604: [liquibase-aws-license-service: //github add env : AWS_REGION](https://github.com/liquibase/liquibase-aws-license-service/commit/8a5a9e2e7671e35574f0ed0e1b3c84a5e9b39d26)

**Comment by sayaliM0412** [comment]
PR not required as one or the other tag would always exist. 
Real issue fixed for DAT-18604: [liquibase-aws-license-service: //github add env : AWS_REGION](https://github.com/liquibase/liquibase-aws-license-service/commit/8a5a9e2e7671e35574f0ed0e1b3c84a5e9b39d26)

**Pull request closed without merging**
